version: "3.7"

volumes:
  elasticsearch_data:
  n8n_data:

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    restart: unless-stopped
    network_mode: host
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=hive
      - bootstrap.memory_lock=true
      - script.allowed_types=inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  cortex:
    image: thehiveproject/cortex:latest
    container_name: cortex
    restart: unless-stopped
    network_mode: host
    cap_add:                    # ADD THIS
      - NET_ADMIN               # ADD THIS
      - NET_RAW                 # ADD THIS (optional, for raw sockets)
    environment:
      - JOB_DIRECTORY=/opt/cortex/jobs
      # Replace with your actual OpenAI API key
      - OPENAI_API_KEY=<open-api-api-key>
      - OPENAI_MODEL=gpt-3.5-turbo
      # Replace with your actual TheHive URL and API key
      - THEHIVE_URL=<the-hive-url>
      - THEHIVE_API_KEY=<the-hive-api-key>
      # AI Configuration
      - AI_DEBUG=false
      - AI_TIMEOUT=30
      - AI_MAX_TOKENS=500
      - AI_TEMPERATURE=0.1
      - AI_MAX_RETRIES=3
      # Python Configuration
      - PYTHONPATH=/opt/cortex/responders
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./cortex/application.conf:/etc/cortex/application.conf
      - ./cortex/jobs:/opt/cortex/jobs
      - ./cortex/log/:/var/log/cortex
      - ./cortex/responders:/opt/cortex/responders
      - ./scripts:/opt/scripts:ro
      - /tmp:/tmp
    entrypoint: ["/bin/bash", "/opt/scripts/cortex-init.sh"]

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678
      - EXECUTIONS_PROCESS=main
      - DB_TYPE=sqlite
      - DB_SQLITE_PATH=/home/node/.n8n/database.sqlite
      # Replace with your actual OpenAI API key
      - OPENAI_API_KEY=sk-your-actual-openai-api-key-here
      - AI_MODEL=gpt-3.5-turbo
    volumes:
      - n8n_data:/home/node/.n8n
